// import "@/styles/globals.css";

// import { type Metadata, type Viewport } from "next";
// import { Geist } from "next/font/google";
// import { Navigation } from "@/components/navigation";

// export const metadata: Metadata = {
//   title: "FRAI AI Boilerplate",
//   description: "Advanced AI-powered development framework with LangGraph agents and RAG capabilities",
//   keywords: ["AI", "LangGraph", "Claude", "RAG", "FastAPI", "Next.js", "Boilerplate"],
//   authors: [{ name: "FRAI Team" }],
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export const viewport: Viewport = {
//   width: "device-width",
//   initialScale: 1,
// };

// const geist = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`dark ${geist.variable}`}>
//       <body className="antialiased bg-background text-foreground">
//         <Navigation />
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Navigation } from "@/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
