"""empty message

Revision ID: d3bc131ebde3
Revises: e4a855c21331
Create Date: 2025-08-20 21:16:29.258521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bc131ebde3'
down_revision = 'e4a855c21331'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
