# Development environment configuration
services:
  api-dev:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.dev
      target: development
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      db-dev:
        condition: service_healthy
    volumes:
      - ../../src:/code/src
      - ../../tests:/code/tests
      - ../../.env:/code/.env
    environment:
      - POSTGRES_SERVER=db-dev
      - POSTGRES_PORT=5432
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true

  db-dev:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-interview_insight_dev_db}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data-dev:
